dependencies:
  apt:
    - libzstd-dev
stages:
  development:
    - RUN yes | pecl install redis && docker-php-ext-enable redis
services:
  cache:
    image: redis:6.0.8
    restart: always
depends_on:
  - igbinary
