RUN mkdir -p storage

WORKDIR storage
RUN mkdir -p logs && \
    mkdir -p framework && \
    mkdir -p framework/cache && \
    mkdir -p framework/cache/data && \
    mkdir -p framework/sessions && \
    mkdir -p framework/testing && \
    mkdir -p framework/views
WORKDIR ..
