RUN mkdir -p /var/www/.npm /.npm /.config
RUN chown -R www-data: /var/www/.npm /.npm /.config
RUN chmod -R 775 /var/www/.npm /.npm /.config

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN npm set progress=false
