RUN mkdir -p /var/www/.composer /.composer
RUN chown -R www-data: /var/www/.composer /.composer
RUN chmod -R 777 /var/www/.composer /.composer

ARG COMPOSER_VERSION

RUN install-php-extensions @composer-${COMPOSER_VERSION}
