#!/usr/bin/with-contenv sh

. /etc/supervisor-config.sh

echo "Registering service with consul..."

PAYLOAD=$(envsubst '${NAME} ${IP} ${PORT} ${ID}' </etc/consul/payloads/register.json)

curl -s -X PUT --data "$PAYLOAD" \
    http://consul:8500/v1/agent/service/register?replace-existing-checks=true
